Controllers/CriarNovoUsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using ProvaPortal.Models;
//Delete from Usuarios where Id = 10;
namespace ProvaPortal.Controllers
{
    public class CriarNovoUsuarioController : Controller
    {
        private readonly ProfessorRepository _professorRepository;
        public CriarNovoUsuarioController(ProfessorRepository professorRepository)
        {
            _professorRepository = professorRepository;
        }

        public IActionResult CriarNovoUsuarioDeslogado()
        {
            try
            {
                return View();
            }
            catch
            {
                TempData["MensagemErro"] = "Ops, sem conexão com o banco de dados! Aguarde alguns minutos e tente novamente.";
                return View("Erro", "Login");
            }
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult CriarNovoUsuarioDeslogado(ProfessorModel professor)
        //{
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            if(professor.SenhaProfessor == professor.ConfirmarSenhaProfessor)
        //            {
        //                TempData["MensagemSucesso"] = "Novo usuário adicionado com sucesso!";
        //                _professorRepository.AddProfessor(professor);
        //                return RedirectToAction("Index", "Login");
        //            }

        //            TempData["MensagemErro"] = "Senha não confere! Verifique as senhas e tente novamente.";
        //        }
        //        return View();
        //    }
        //    catch (Exception)
        //    {
        //        TempData["MensagemErro"] = "Ops, sem conexão com o banco de dados! Aguarde alguns minutos e tente novamente.";
        //        return View("Erro", "Usuario");
        //    }

        //}

    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProvaPortal.Models;
using ProvaPortal.Repository.Interface;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;

namespace ProvaPortal.Controllers
{
    public class LoginController : Controller
    {
        private readonly IProfessorRepository _professorRepository;
        private readonly ISessao _sessao;
        private readonly HttpClient _httpClient;
        private readonly IMapper _mapper;
        private readonly string API_ENDPOINT = "https://localhost:44389/api/login/entrar";

        public LoginController(IProfessorRepository professorRepository, ISessao sessao, HttpClient httpClient, IMapper mapper)
        {
            _professorRepository = professorRepository;
            _sessao = sessao;
            _httpClient = httpClient;
            _mapper = mapper;
            _httpClient.BaseAddress = new Uri(API_ENDPOINT);
        }

        public IActionResult Index()
        {
            var usuarioLogado = _sessao.BuscarSessaoUsuario();
            if (usuarioLogado != null)
            {
                return RedirectToAction("Index", "Provas");
            }

            return View();
        }

        public IActionResult Sair()
        {
            _sessao.RemoverSessaoUsuario();
            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult<ProfessorDTO>> Entrar(LoginModel novoLogin)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var loginModel = new LoginModel
                    {
                        Login = novoLogin.Login,
                        Senha = novoLogin.Senha,
                    };

                    var novoUsuarioJson = JsonConvert.SerializeObject(loginModel);

                    _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    var content = new StringContent(novoUsuarioJson, Encoding.UTF8, "application/json");

                    HttpResponseMessage response = await _httpClient.PostAsync("/api/login/entrar", content);

                    if (response.IsSuccessStatusCode)
                    {
                        var responseContent = await response.Content.ReadAsStringAsync();

                        try
                        {
                            var responseData = JsonConvert.DeserializeObject<ProfessorDTO>(responseContent);

                            if (responseData != null)
                            {
                                _sessao.CriarSessaoUsuario(responseData);

                                TempData["MensagemSucesso"] = "Login feito com sucesso!";
                                return RedirectToAction("Index", "Provas");
                            }
                            else
                            {
                                ModelState.AddModelError("", "Dados do professor não encontrados na resposta da API.");
                            }
                        }
                        catch (JsonException ex)
                        {
                            ModelState.AddModelError("", "Erro ao desserializar a resposta JSON da API: " + ex.Message);
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Erro ao consultar o usuário na API. Status: " + response.StatusCode);
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Erro ao consultar o usuário: " + ex.Message);
                }
            }

            return View(novoLogin);
        }
    }
}

Views/Login/Erro.cshtml
<head>
    <meta charset="UTF-8">
    <title>Error</title>
    <style>
        body {
            font-family: 'Titillium Web', sans-serif;
            color: #666666;
            text-align: center;
        }

        .box {
            background-color: #fff;
            width: 500px;
            margin: 50px auto;
        }

        #title {
            font-size: 30px;
            margin-top: 25px;
        }

        #logo-task {
            width: 100px;
        }
    </style>
</head>
<body>
    <div class="box display-3">
        <div id="title">
            404
        </div>
        <a asp-controller="Login" asp-action="Index">
            <img src="https://cdn-0.emojis.wiki/emoji-pics/facebook/man-shrugging-facebook.png" id="logo-task">
        </a>
    </div>
</body>

Views/Login/Index.cshtml
@model LoginModel
@{
    Layout = "_layoutDeslogado";
    ViewData["Title"] = "Login";
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["MensagemErro"]
    </div>
}

<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">

<div id="loadingOverlay" class="overlay">
    <div class="loader"></div>
    <div class="loading-text">Carregando...</div>
</div>

<div id="login" class="container">
    <div class="row-fluid">
        <div class="span12">
            <div class="login well well-small">
                <form class="login-form" id="UserLoginForm" asp-controller="Login" asp-action="Entrar" method="post" novalidate>
                    <div class="control-group">
                        <div class="input-prepend">
                            <span class="add-on"><i class="icon-user"></i></span>
                            <input id="UserUsername" asp-for="Login" type="text" class="form-control" placeholder="Usuário" autofocus required>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="input-prepend">
                            <span class="add-on"><i class="icon-lock"></i></span>
                            <input id="UserPassword" asp-for="Senha" type="password" class="form-control caps-lock-warning" value="" placeholder="Senha" autofocus required>
                        </div>
                        <div id="capsLockWarning" class="text-danger"></div>
                    </div>
                    <div class="text-center fs-6">
                        <a asp-action="RedefinirSenha" asp-controller="Login">Esqueceu a senha?</a> ou <a asp-action="CriarNovoUsuarioDeslogado" asp-controller="CriarNovoUsuario">Crie uma Conta!</a>
                    </div>
                    <div class="control-group">
                        <p class="submit"><input type="submit" name="commit" value="Login"></p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var loadingOverlay = document.getElementById("loadingOverlay");
        var UserLoginForm = document.getElementById("UserLoginForm");
        var passwordInput = document.getElementById("UserPassword");
        var capsLockWarning = document.getElementById("capsLockWarning");

        function mostrarLoading() {
            loadingOverlay.style.display = "block";
        }

        function ocultarLoading() {
            loadingOverlay.style.display = "none";
        }

        UserLoginForm.addEventListener("submit", function (e) {
            e.preventDefault();
            mostrarLoading();

            setTimeout(function () {
                UserLoginForm.submit();
            }, 1000);
        });

        passwordInput.addEventListener("keydown", function (e) {
            var capsLockEnabled = e.getModifierState && e.getModifierState("CapsLock");

            if (capsLockEnabled) {
                passwordInput.classList.add("caps-lock-enabled");
                capsLockWarning.innerHTML = "Caps Lock está ativado";
            } else {
                passwordInput.classList.remove("caps-lock-enabled");
                capsLockWarning.innerHTML = "";
            }
        });
    });
</script>