Controllers/ProfessorsController.cs
using Microsoft.AspNetCore.Mvc;
using ProvaPortal.Repository.Interface;
using ProvaPortal.Filters;

namespace ProvaPortal.Controllers
{
    [PaginaSomenteAdmin]
    public class ProfessorController : Controller
    {
        private readonly IProfessorRepository _professorRepository;
        private readonly HttpClient _httpClient;
        private readonly string API_ENDPOINT = "https://localhost:44389/api/professor";

        public ProfessorController(IProfessorRepository professorRepository)
        {
            _professorRepository = professorRepository;
            _httpClient = new HttpClient
            {
                BaseAddress = new Uri(API_ENDPOINT)
            };
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                HttpResponseMessage response = await _httpClient.GetAsync("/api/professor");
                response.EnsureSuccessStatusCode();

                var professores = await response.Content.ReadAsAsync<IEnumerable<ProfessorDTO>>();
                return View(professores);
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Erro ao buscar professores: " + ex.Message;
                return View(new List<ProfessorDTO>());
            }
        }

        public async Task<IActionResult> Detalhes(int id)
        {
            try
            {
                HttpResponseMessage response = await _httpClient.GetAsync($"/api/professor/{id}");
                response.EnsureSuccessStatusCode();

                var professor = await response.Content.ReadAsAsync<ProfessorDTO>();
                return View(professor);
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Erro ao buscar detalhes do professor: " + ex.Message;
                return View(new ProfessorDTO());
            }
        }

    }
}

Views/Shared/Components/Menu/Default.cshtml
@*@using ProvaPortal.Models.DTOs;*@
@model ProfessorModel
@*@model ProfessorDTO*@

<div class="container">
    <a class="navbar-brand"@* asp-area="" asp-controller="Provas" asp-action="Index"*@> Olá @Model.NomeAbreviado</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>''
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <ul class="navbar-nav flex-grow-1">

            @if (Model.Perfil == ProvaPortal.Models.Enum.Perfil.Administrador)
            {
                @*<li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Professor" asp-action="ListarProfessores">Professores</a>
                </li>*@
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Provas" asp-action="VisualizarTodasProvas">Provas Enviadas</a>
                </li>
            }
            @if (Model.Perfil == ProvaPortal.Models.Enum.Perfil.Professor)
            {
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Provas" asp-action="Index">Provas</a>
                </li>
            }

            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Sair">Sair</a>
            </li>
        </ul>
    </div>
</div>